typography_spectrum: 0.15231
color:
  brandColors:
    - '#ffffff'
    - '#05060a'
    - '#b5b8c7'
    - '#8a8889'
    - '#2c3c10'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75165
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Robert Regler
  email: regler@gmx.de
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1641371d-136b-444c-8568-ad3ab6a50142.gif
name: emijel RC
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Event: LKW Treffen Pöhl 2016'
    id: 227ec2b0-3b96-45a1-81b8-60d0c1d2f4e8
    type: content
  - name: 'Car: Stampede im Staub'
    id: be1e47d0-94c8-4d80-80af-708d6ddabec5
    type: content
  - name: 'Car: MAN KAT 8x8x4 "KATweazle"'
    id: 3c006095-4b99-4703-be1b-8cbafb625179
    type: content
  - name: 'Car: Subaru in Greenwood 13.2.2016'
    id: 20637bfe-ad1f-49a3-8f83-fb97fede81a3
    type: content
favicon: null
title: emijel RC
description: RC Artist
purpose: []
