typography_spectrum: 0.15231
color:
  brandColors:
    - '#ffffff'
    - '#05060a'
    - '#b5b8c7'
    - '#8a8889'
    - '#2c3c10'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75165
analytics:
  google: null
  facebook: null
  twitter: null
name: emijel rc
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: emijel RC
purpose: []
