name: emijel rc
favicon: null
layout_spectrum: 0.75199
typography_spectrum: 0.15231
title: emijel rc
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#05060a'
    - '#b5b8c7'
    - '#8a8889'
    - '#2c3c10'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
